# Generated by Django 4.0.6 on 2022-07-18 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=250, verbose_name='Note Text')),
                ('hecho', models.BooleanField(default=False, verbose_name='Done')),
            ],
        ),
    ]
